//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency
    {
        public agency()
        {
            this.orphans = new HashSet<orphan>();
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string contacNo { get; set; }
        public string email { get; set; }
        public string imageUrl { get; set; }
        public long balance { get; set; }
    
        public virtual ICollection<orphan> orphans { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
