//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class orphan
    {
        public int id { get; set; }
        public string name { get; set; }
        public string contactNo { get; set; }
        public string address { get; set; }
        public bool isAccepted { get; set; }
        public Nullable<int> aid { get; set; }
        public Nullable<int> vid { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual user user { get; set; }
    }
}
