//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public Nullable<int> donatorid { get; set; }
        public Nullable<int> reciverid { get; set; }
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public long amount { get; set; }
    }
}
