//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.orphans = new HashSet<orphan>();
            this.tokens = new HashSet<token>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<int> aid { get; set; }
        public long balance { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual ICollection<orphan> orphans { get; set; }
        public virtual ICollection<token> tokens { get; set; }
    }
}
